spring:
  application:
    name: movie-catalog-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

test:
  config:
    location: "Inside ${spring.application.name} Package(Jar)"

